
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-{{.Values.metadata.name}}
{{  template "labels" . }}
  name:  {{ .Release.Name }}-{{.Values.metadata.name }}
spec:
  ports:
  - name: bakehouseport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bakehouse
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}